version: '3'
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: 'directus'

  directus:
    restart: always
    image: directus/directus:latest
    volumes:
      - extensions:/directus/extensions
    networks:
      - traefik-public
    depends_on:
      - database
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: '${DB_PASSWORD}'

      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      
      EMAIL_FROM: '${EMAIL_FROM}'
      EMAIL_TRANSPORT: smtp
      EMAIL_SMTP_HOST: '${EMAIL_SMTP_HOST}'
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: '${EMAIL_FROM}'
      EMAIL_SMTP_PASSWORD: '${EMAIL_SMTP_PASSWORD}'
      EMAIL_SMTP_POOL: "false"
      EMAIL_SMTP_SECURE: "false"
      
      REFRESH_TOKEN_COOKIE_SAME_SITE: '${REFRESH_TOKEN_COOKIE_SAME_SITE}'
      REFRESH_TOKEN_COOKIE_SECURE: '${REFRESH_TOKEN_COOKIE_SECURE}'
      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      PUBLIC_URL: 'https://${PUBLIC_URL}'
      
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8055"
        - "traefik.http.routers.qrcode-me-directus.rule=Host(`${PUBLIC_URL}`)"
        - "traefik.http.routers.qrcode-me-directus.tls=true"
        - "traefik.http.routers.qrcode-me-directus.tls.certresolver=letsencrypt"
        - "traefik.http.services.qrcode-me-directus.loadbalancer.server.port=8055"


networks:
  traefik-public:
    driver: overlay
    external: true
    attachable: true


volumes:
  db:
  extensions:
